<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>iip</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="IO.fs" />
    <Compile Include="UseCase.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Argu" Version="6.2.5" />
    <PackageReference Include="FsHttp" Version="15.0.3" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.62.0" />
  </ItemGroup>

</Project>
